### PR TITLE
Add output to SPE1CASE2 summary

### PR DESCRIPTION
**Pull request by totto82**
- productivity index of the phases
- phase well potential for injectors and producers

### CODE REVIEW

**Comment by alfbr** [comment]
This also looks good. Feel free to self-merge when ready.

**Comment by totto82** [comment]
@akva2 Can I test this PR from opm-tests? Or do I need to hijack a PR in opm-simulators to test this?

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
fixed.

**Comment by alfbr** [comment]
@totto82 , did you forget this one?

**Comment by alfbr** [comment]
@totto82 have you still forgotten this one? If no comment, I will close it by end of tomorrow.

**Comment by alfbr** [comment]
Closing as warned. Please re-open if you want the test in.

**Pull request closed without merging**
