### PR TITLE
Added results for the SPE1CASE1_METRIC_VFP1 case using flow and eclipse. 

### PR DESCRIPTION
**Pull request by andreatlonn**

### CODE REVIEW

**Comment by alfbr** [comment]
Thanks for the new case! Please remove the trailing spaces on the two lines on spe1/SPE1CASE1.DATA, as it looks like you made changes to this file.

Please remove vfpprod_spe1/.directory, vfpprod_spe1/opm-simulation-reference/.directory and vfpprod_spe1/SPE1CASE1_METRIC_VFP1.DATA~  from git.

Please change copyright notices from Statoil to Equinor.

Please update description of the deck in the header to reflect that this is a test for VFP.

Please remove vfpprod_spe1/SPE1CASE1_METRIC_VFP1_EC.DATA.

In addition, I suggest removing the Eclipse solutions on this case. This is a bit of a general discussion, so I encourage anybody disagreeing to voice their concern about not including reference solutions from Eclipse. Hence I will hang on a bit before merging.

**Comment by akva2** [comment]
squash the commits / redo the branch. we do not want those eclipse files in history at all.

**Comment by akva2** [comment]
just in case: https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

**Comment by alfbr** [comment]
Please also remove PRT and DEBUG file, and squash again. Then add license and copyright headers to the include files.

**Comment by alfbr** [comment]
Excellent, thanks for your patience!

**Pull request merged**
