### PR TITLE
update reference data for spe9 spe3 multpvv_model2 spe1 spe5 spe9group fetkovich_2d base_model2 spe12p editnnc_model2 ctaquifer_2d_oilwater spe1nowells polymer2d multflt_model2 faults_model_1 base_model_1 wecon_wtest polymer_injectivity multiply_tranxyz_model2 spe1_metric_vfp1 msw_2d_h spe1_foam hysteresis_model2 udq spe12 msw_3d_hfa multregt_model2 polymer_oilwater msw_model_1 swatinit_model2 nnc endscale_model2 multxyz_model2 spe1oilgas spe1thermal

### PR DESCRIPTION
**Pull request by jenkins4opm**
Reason: https://github.com/OPM/opm-common/pull/876

libecl         = 4d92ac7982be3a7c5fbca1bcad694f020fd872af
opm-common     = f5598d6e14412940aaaf29368849dbf745af2dc9
opm-grid       = bdcd38acc39c9a33d40bc1eb78548cf68002040c
opm-material   = a663bb45324df35734e3b6c79998e4e3fdea7a0b
ewoms          = a42a16fe2c5120e7e4a966ca538d32ec78f37c55
opm-simulators = f5598d6e14412940aaaf29368849dbf745af2dc9

### CODE REVIEW

**Comment by alfbr** [comment]
I guess this is the one that should be merged, since it is the last one.

**Comment by akva2** [comment]
yes, this is active.

**Comment by GitPaean** [comment]
@akva2 , any clue why `SMSPEC ` is always updated now when `update_data`?

**Comment by akva2** [comment]
i don't know what, but there's a few values at the end of the file that changes. gut reaction is there's a timestamp or a runtime in there, but i don't really know these file formats all that well.

@tskille please advice.

**Comment by GitPaean** [comment]
> i don't know what, but there's a few values at the end of the file that changes. gut reaction is there's a timestamp or a runtime in there, but i don't really know these file formats all that well.

Now I remember something might be relevant. It happened before, there is some value might be a little random that caused the problem.  I remember there was a fix to address that and I am not sure why this happens again.

**Comment by GitPaean** [comment]
related discussion was in the following links. 

https://github.com/OPM/opm-simulators/pull/1685

https://github.com/equinor/libecl/pull/553

Not sure the current problem is related to similar reasons.

**Pull request merged**
