### PR TITLE
changing the number of segments for 2D_H__

### PR DESCRIPTION
**Pull request by GitPaean**
to protect the bug-fix from PR https://github.com/OPM/opm-simulators/pull/4239 . 

With the above PR, flow can handle the changing of the segment numbers to some extent.

### CODE REVIEW

**Comment by GitPaean** [comment]
If someone volunteers for more sophisticated design, feel free to do so. I just modified a simple case that I manually wrote before, which is easy for me to do.

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
jenkins build this update_data please

**Comment by bska** [comment]
> update_data

Note that it's generally not possible to update the reference solutions from a PR in opm-tests.  The way to do this is to trigger the data update from a PR in an upstream repository such as opm-simulators or opm-common.

**Comment by GitPaean** [comment]
The reference update of https://github.com/OPM/opm-tests/pull/849 is merged to this PR for jenkins test.

**Comment by GitPaean** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
Thanks a lot for the updates.  This looks good to me and I'll merge into master.

**Pull request merged**
