### PR TITLE
adding more output for UDQ_WCONPROD

### PR DESCRIPTION
**Pull request by GitPaean**
especially regarding to the guide rates. 

So when testing failures happens, we can see more clearly regarding to the guide rates comparison.

### CODE REVIEW

**Comment by alfbr** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
It is green from Jenkins. @bska , can you have a look. It is ready to go in from my side.

**Pull request merged**
