### PR TITLE
Add Test Cases for Aquifer Restart Functionality

### PR DESCRIPTION
**Pull request by bska**
Differ from their base counterparts in the SOLUTION section, and in adding the `SKIPREST` keyword to the beginning of the SCHEDULE section.

### CODE REVIEW

**Comment by bska** [comment]
An example of the differences are from the `2D_OW_CTAQUIFER` model
```diff
--- ./2D_OW_CTAQUIFER.DATA	2021-04-09 12:02:41.368320117 +0200
+++ ./2D_OW_CTAQUIFER_RESTART.DATA	2021-06-17 15:13:24.071251648 +0200
@@ -783,24 +783,9 @@
 ---------------------------------------------------------------------------------
 SOLUTION
 
+RESTART
+  2D_OW_CTAQUIFER 15 /
 
-
-EQUIL
--- Datum    P     woc     Pc   goc    Pc  Rsvd  Rvvd
-   2525.   270   2600    0.0  2200.  0.0   1*   0   0/  
-
-AQUCT
--- AqID  Datum   Pres    Perm   Poro   Cr+Cw    Re     hz      Ang    pvt# tdpd#
-    1    2000.0     269    100   .3  3.0e-5     330     10     360.0    1     2 /
-/
-
-AQUANCON
--- Aq#     I1 I2  J1   J2  K1 K2 FACE
-    1      1  1  1    1   1  1  J- 1.0 1.0 NO/
---    1      1  33  1    33   1  2  J+  1.0 1.0 NO/
---    1      1  33  1    33   1  2  I-  1.0 1.0 NO/
---    1      1  33  1    33   1  2  I+  1.0 1.0 NO/ 
-/
 DEBUG
 12 /
 
@@ -834,6 +819,8 @@
 
 SCHEDULE
 
+SKIPREST
+
 OPTIONS
 136* 2
 /
```
We intend to activate these as proper restart/regression tests once the functionality lands.

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
jenkins build this please

**Comment by tskille** [comment]
Thanks a lot @bska . I think this will be very good models to be used for regression testing of flow restart. Would you like me to merge these or are these still work in progress ?

**Comment by bska** [comment]
> Would you like me to merge these or are these still work in progress ?

These are ready for merging whenever you see fit.

**Comment by tskille** [comment]
excellent, merging now.

**Pull request merged**
