### PR TITLE
Add SPE1 case where grid data is loaded with IMPORT

### PR DESCRIPTION
**Pull request by joakim-hove**

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by alfbr** [comment]
Please include a short sentence in the file header, the PR title suffices: "SPE1 case where grid data is loaded with IMPORT"

**Comment by joakim-hove** [comment]
> Please include a short sentence in the file header,

Done

**Comment by alfbr** [comment]
Thanks! Merging.

**Pull request merged**
