### PR TITLE
Automatic Reference Data Update for PR https://github.com/OPM/opm-simulators/pull/4821

### PR DESCRIPTION
**Pull request by jenkins4opm**
Reason: PR https://github.com/OPM/opm-simulators/pull/4821

opm-common     = 5010643b0d8d9cc0f33a90f3fbd785084165eb7e
opm-grid       = 0276599f9eb63de44c3e4f1560f134d8ff77c03d
opm-models     = 567da9b6d9722087e98721edf00aacb6afb14e6c
opm-simulators = 5adf39d3490379971804d6bdb30c03898681e652

### Changed Tests ###

  * numerical_aquifer_3d_2aqu
  * numerical_aquifer_3d_1aqu

### CODE REVIEW

**Comment by GitPaean** [comment]
Just curious, should the UNSMRY files be changed?

**Comment by GitPaean** [comment]
Maybe they are not changed, just updated along with other files, like INIT files.

**Comment by akva2** [comment]
there are some changes, see https://ci.opm-project.org/job/opm-simulators-PR-builder/lastSuccessfulBuild/artifact/data_diff/*view*/

**Comment by GitPaean** [comment]
Thanks. I see them now.

**Comment by bska** [comment]
>> there are some changes,
>
> Thanks. I see them now.

Right&ndash;I don't think those changes, other than the ones to the `.EGRID` and `.INIT` files (`NNC1`, `NNC2`, and `TRANNNC` arrays), are caused by this particular change (OPM/opm-simulators#4821).  I suspect (hope) they're the result of cumulative changes over time&ndash;the previous update to these files were in #934 as a result of OPM/opm-simulators#4533, and before that #908 triggered by OPM/opm-simulators#4370&ndash;which are now being materialised because we're updating the `EGRID` and `INIT` files.

**Comment by bska** [comment]
I'm closing this.  Another update (#1039) proves that the changes to dynamic result files are **not** generated by cumulative changes over time.  I'll look more closely into those before I'm confident that we can update the reference results.

**Pull request closed without merging**
