### PR TITLE
WVFPEXP Tests - WIP

### PR DESCRIPTION
**Pull request by OPMUSER**
Test model is based on a tartan anticline grid in order to induce instabilities for testing the various WVFPEXP keyword options in the SCHEDULE section.

WVFPEXP-01:  WVDPEXP(IMPEXP) =  IMP and WVFPEXP(CONTROL) = NO.
WVFPEXP-01:  WVDPEXP(IMPEXP) =  IMP and WVFPEXP(CONTROL) = YES2.

Preliminary findings:
(1) Well control modes not consistent with commercial simulator.
(2) OPM Flow keeps wells open despite the IPR not intersecting the VFP curves.

### CODE REVIEW

**Comment by alfbr** [comment]
jenkins build this please

**Comment by alfbr** [comment]
Thanks for the contribution! Please remove Eclipse binaries, we do not keep them under version control. Other than that, this is good to go.

**Comment by alfbr** [comment]
Thanks for the fix, in it goes! These cases are highly appreciated, looking forward to getting them under regression testing :-)

**Comment by totto82** [comment]
The WVFPEXP test cases mixes capital/non capital letters. i.e. they don't run on my linux machine without modifications 

```
 PATHS
         'MODEL05'   '../model5/include'                                        /
-        'WVFPEXP'   '../WVFPEXP/include'                                       /
+        'WVFPEXP'   '../wvfpexp/include'                                       /^M
 /
 --
 --       MESS  COMMT WARN  PROBL ERROR BUG   MESS COMMT WARN  PROBL ERROR BUG
@@ -197,7 +197,7 @@ NOECHO
 --       LOAD INCLUDE FILE - GRID DATA
 --
 INCLUDE
-         '$WVFPEXP/WVFPEXP-GRID01.INC'  /
+         '$WVFPEXP/WVFPEXP-GRID01.inc'  /^M
 
```

**Pull request merged**
