### PR TITLE
Aquifers Re-Factoring

### PR DESCRIPTION
**Pull request by OPMUSER**
Combining four aquifer cases into one directory with documentation - WIP

### CODE REVIEW

**Comment by OPMUSER** [comment]
Ready for review.

**Comment by bska** [comment]
jenkins build this please

**Review by bska — COMMENTED** [review]
I appreciate the work here, and I think it should go in, possibly with a couple of additional summary vectors.  That said, I'm on the fence on adding the ECLIPSE reference solutions.  We've usually shied away from doing that in the past even if having that data is useful for comparison purposes.

What do you think, @alfbr?

**Comment by OPMUSER** [comment]
> I  appreciate the work here, and I think it should go in, possibly with a couple of additional summary vectors. That said, I'm on the fence on adding the ECLIPSE reference solutions. We've usually shied away from doing that in the past even if having that data is useful for comparison purposes.

We should definitely have the comparison plots versus the commercial simulator, for a variety of reasons. Having the commercial results is maybe not so important, but if we say we don't keep the commercial results then we need to delete them from the other tests as well, just to be consistent. A halfway solution would be just to keep the commercial simulator's summary output files.

To be clear, we  definitely should have the comparison plots versus the commercial simulator, but it is not strictly necessary to have all the commercial simulator results files.

**Comment by OPMUSER** [comment]
Will rerun the cases using the TUNING keyword to get a better comparison with the commercial simulator, and then update the plots. But for now it off to the Isles :-)

**Comment by OPMUSER** [comment]
@bska This is now ready for review.

**Pull request merged**
