### PR TITLE
Output problem of GRUPTREE case has been fixed.

### PR DESCRIPTION
**Pull request by joakim-hove**

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins bulid this please

**Comment by bska** [comment]
Does "output problem" here refer to OPM/opm-common#2674 to does it refer to something else?

**Comment by joakim-hove** [comment]
> Does "output problem" here refer to OPM/opm-common#2674 or does it refer to something else?

It refers to: https://github.com/OPM/opm-common/pull/2725 - which does not immediately look like an output problem.

**Comment by joakim-hove** [comment]
jenkins build this please

**Pull request merged**
