### PR TITLE
Add trailing "-- $REPORT_STEP" to DATES keywords

### PR DESCRIPTION
**Pull request by joakim-hove**

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
Thanks.  This looks good to me.

**Comment by bska** [comment]
@akva2 : This PR is ready for merging in my opinion so we can use it as a basis for experimenting with push notifications in opm-tests if you'd like.

**Comment by akva2** [comment]
okay, i don't have access to it so those with access need to configure the webhook on the opm-tests repo, like described here https://stackoverflow.com/questions/48093039/jenkins-github-hook-trigger-for-gitscm-polling @alfbr i guess ?

**Pull request merged**
