### PR TITLE
Add second PLMIX region

### PR DESCRIPTION
**Pull request by totto82**
Needs fix in OPM/opm-models#588

### CODE REVIEW

**Comment by bska** [comment]
@totto82 : Is this ready for merging now?

**Comment by totto82** [comment]
yes. he values for the regions are the same i.e. the results of the test case should not change i.e. we can merge this without any update of data.

**Comment by bska** [comment]
> the results of the test case should not change i.e. we can merge this without any update of data.

Cool.  Do you want to run build check just in case?

**Comment by totto82** [comment]
Can I do that from opm-tests?

**Comment by bska** [comment]
> Can I do that from opm-tests?

Yes.  We can run "build this please" from opm-tests, but we can't trigger reference data updates from this repository.

**Comment by totto82** [comment]
jenkins build this please

**Comment by bska** [comment]
Build check was successful.  I'll merge into master.

**Pull request merged**
