### PR TITLE
Test data sets for the use of the keyword WELPI

### PR DESCRIPTION
**Pull request by jalvestad**
The pull requests contain a data set to test the implementation of the keyword WELPI in flow. 

The data set: 10_1A_BASE_MODEL2_WELPI_DEF-RO.DATA 
contain use of WELPI for
i.   Production wells with preferred phase (OIL, GAS)
  PROD1 - OIL
  PROD2 - OIL
  PROD3 - GAS
ii.  Injection wells with preferred phase (GAS, WATER)
  INJ1 - WATER
  INJ2 - GAS
All wells get their PI values adjusted once-

The wells PROD2, PROD3 and INJ2 get the PI adjusted an extra time.

### CODE REVIEW

**Comment by tskille** [comment]
I would recommend that we add CTFAC vector for all connection to the summary section in the data file

```
CTFAC 
 'PROD1' /
 'INJ1'  /
/
```

WELPI will cause the simulator to re-calculate these.

**Comment by jalvestad** [comment]
Thanks for good comment, I have added CTFAC for all wells and all connections, due to different PI-changes for all wells.

**Comment by jalvestad** [comment]
The test case is ready for review and merge from my side.

**Comment by alfbr** [comment]
Thank you, highly appriciated! Just a few nits:
Please consider changing the file name to something shorter, e.g., 0B_WELPI_MODEL2.DATA
Please include a short description of what is tested in the header of the DATA-file.

**Comment by jalvestad** [comment]
The test dataset has been changed to add use of WELPI at or before the opening of a well.  The dataset is considered ready for merge.

**Comment by alfbr** [comment]
jenkins build this please

**Pull request merged**
