### PR TITLE
Remove model1-MULT cases and replace with MULT cases and documentation

### PR DESCRIPTION
**Pull request by OPMUSER**
Deleted model1-MULT directory and cases, and replace with mult directory and cases. Also document runs using Markdown, and removed ODP file documentation.

### CODE REVIEW

**Comment by OPMUSER** [comment]
Ready for review.

**Comment by bska** [comment]
jenkins build this please

**Comment by OPMUSER** [comment]
Jenkins is happy, so can this go in?

**Review by bska — APPROVED** [review]
Thanks for the updates and apologies about the delay.  I'll merge this into the master branch now.

**Pull request merged**
