### PR TITLE
Actionx restart + reference data

### PR DESCRIPTION
**Pull request by akva2**
This is https://github.com/opm/opm-tests/pull/400 including https://github.com/OPM/opm-tests/pull/405

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
Not exactly a smooth ride but there you have it @joakim-hove

**Comment by joakim-hove** [comment]
> Not exactly a smooth ride but there you have it @joakim-hove

Thanks a lot for the assistance; I understand the faulty deck from my hand was a part of the stumbling - sorry about that.

The part I committed is ready for merge, but since this PR now contains an unrelated commit which I am not familiar with I will let it linger.

**Comment by akva2** [comment]
only thing appended is the data update.

**Pull request merged**
