### PR TITLE
Remove COORDSYS

### PR DESCRIPTION
**Pull request by OPMUSER**
Remove COORDSYS from test cases.

### CODE REVIEW

**Review by bska — APPROVED** [review]
Looks good to me.  I'll run a build check just to be sure we don't accidentally break anything and then I'll merge if successful.

**Comment by bska** [comment]
jenkins build this please

**Comment by OPMUSER** [comment]
@baksa I going to push the update documentation as well for all cases, the Markdown file an the plots, within the hour..

**Comment by OPMUSER** [comment]
Now ready for merging.

**Comment by bska** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
Thanks for the updates.  I'll merge into master.

**Pull request merged**
