### PR TITLE
Adjusted numerical tuning to minimize discretization error.

### PR DESCRIPTION
**Pull request by alfbr**
Just some minor changes to minimize discretization error when running the test with a simulator honouring the tuning keywords.

### CODE REVIEW

**Comment by alfbr** [comment]
jenkins build this please

**Comment by bska** [comment]
> jenkins build this please

That did apparently not take.  I'll try to rerun it.

**Comment by bska** [comment]
jenkins build this please

**Comment by akva2** [comment]
was missing from white list, has been added.

**Comment by alfbr** [comment]
>  I don't think Flow supports WSEGITER as of right now,

True, but comparing results from Flow to alternatives is of interest.

**Comment by bska** [comment]
> > I don't think Flow supports WSEGITER as of right now,
> 
> True, but comparing results from Flow to alternatives is of interest.

Very good.  I'll merge this into master now.  Thanks a lot for the updates.

**Pull request merged**
