### PR TITLE
Test case for flow_onephase_energy

### PR DESCRIPTION
**Pull request by goncalvesmachadoc**
Both simulators work fine now, flow_onephase and flow_onephase_energy.

### CODE REVIEW

**Comment by atgeirr** [comment]
The same questions posed for #441 apply here as well.

**Comment by atgeirr** [comment]
Can the dummy tables here be removed? Can the schedule be shortened?

**Comment by goncalvesmachadoc** [comment]
flow_onephase_energy still has issues, so this case is not ready to go into regression tests.

**Comment by bska** [comment]
@goncalvesmachadoc: Is this the same as the one you added in #500?

**Comment by goncalvesmachadoc** [comment]
Yes, it is. Now the case runs ok.

**Comment by bska** [comment]
> Yes, it is. Now the case runs ok.

Thanks for confirming.  Then I'll just close this as the case is already in the master branch.

**Pull request closed without merging**
