### PR TITLE
Add summary keyword WMCTL to get well control mode

### PR DESCRIPTION
**Pull request by joakim-hove**
To aid in debugging

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this update_data please

**Comment by bska** [comment]
> jenkins build this update_data please

Doesn't work.  You can't update the reference data from a PR in opm-tests

**Comment by joakim-hove** [comment]
Ok - I was afraid og that. How to address this situation?

**Comment by akva2** [comment]
you use a dummy pr in a downstream, then you merge the generated PR and this PR into one branch manually afterwards.

**Comment by alfbr** [comment]
jenkins build this please

**Comment by alfbr** [comment]
jenkins build this opm-tests=830 please

**Comment by bska** [comment]
> jenkins build this opm-tests=830 please

Sadly, I don't think that's going to work.  If I recall correctly there is no way for a build in OPM-Tests to refer to another PR in the same repository.  Please correct me if I'm wrong, @akva2.  The safe way to do these kinds of things is to manually merge the two PRs on your own machine and then create an updated PR that has the changes from both.  If you want to risk it, however, you can "just" merge this one and then trigger a build from the other.

**Comment by alfbr** [comment]
I was afraid of that. Since this change is minimal, and you already gave me the option of merging this first, I will :-) I will wait jenkins to finish first.

**Comment by alfbr** [comment]
Indeed, you were correct. Shamelessly taking advantage of your offer, will merge updated data once green.

**Pull request merged**
