### PR TITLE
Reduced time step size and runtime to improve accuracy.

### PR DESCRIPTION
**Pull request by alfbr**
This is the first step in making this test pass locally for users. The runtime has been significantly reduced while maximum timestep has been significantly reduced. This may be sufficient to make tests pass locally.

### CODE REVIEW

**Comment by alfbr** [comment]
jenkins build this update_data please

**Comment by alfbr** [comment]
I suggest this is merged once an updated reference solution is available. While we still do not know if this fixes the local failures, it presents a much better starting point, and still tests the functionality just as well as before.

**Comment by bska** [comment]
> jenkins build this update_data please

@akva2 : Does Jenkins support updating reference solutions directly from an opm-tests PR?

**Comment by akva2** [comment]
No.

**Comment by alfbr** [comment]
Any suggestions on how to proceed @akva2 ? Should I open up a dummy PR in opm-simulators?

**Comment by akva2** [comment]
the problem is we can't have two opm-tests PRs in a single build. so you won't be able to check the generated data even if you do that. so only way to go about it is a dummy PR in opm-simulators, and then you have to merge the two opm-tests PR's manually (this and the generated data).

**Comment by alfbr** [comment]
I have a couple of more PRs in motion, I suggest we just use one of them. There is no hurry.

**Comment by alfbr** [comment]
I have a well-suited candidate to use to get updated solutions for this case. It is found here https://github.com/OPM/opm-simulators/pull/2553

**Pull request merged**
