### PR TITLE
ACTIONX Tests and Documentation

### PR DESCRIPTION
**Pull request by OPMUSER**
See the ACTIONX.md file for brief documentation and status.

### CODE REVIEW

**Comment by alfbr** [comment]
Thanks for the documentation, this is very helpful! Is this ready for review/merge, or are there more commits coming?

**Comment by OPMUSER** [comment]
@alfbr as you can see from the documentation there are few WIP because of bugs, so I don't know what you would like to do in this case. 

For Phase 1 testing I still need to run WEFAC (which found bug #2708) and fixed with OPM/opm-simulators#3546, and make tests for WTEST and UDQ keywords..

**Comment by alfbr** [comment]
> @alfbr as you can see from the documentation there are few WIP because of bugs, so I don't know what you would like to do in this case.

The test cases are of value by themselves. If you are happy with the data-sets as they are now, I suggest we merge. Putting them under regression testing is for another PR in opm-simulators, and that can follow its own time-line.

**Comment by OPMUSER** [comment]
@alfbr yes that is fine they can be merged.

**Comment by alfbr** [comment]
Excellent, let's be on the safe side and give Jenkins a spin first.

**Comment by alfbr** [comment]
jenkins build this please

**Pull request merged**
