### PR TITLE
Don't Mark .DATA Files as Executable

### PR DESCRIPTION
**Pull request by bska**
They shouldn't be.

### CODE REVIEW

**Comment by bska** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
Can you help to change `FAULTS_MODEL_1.DATA` also?

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
Any reservations against merging this?

**Comment by alfbr** [comment]
No, thanks for the fix!

**Pull request merged**
