### PR TITLE
Switch to Unix EOL Markings

### PR DESCRIPTION
**Pull request by bska**
While here, also remove EOL whitespace.

### CODE REVIEW

**Comment by bska** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins build this please

**Review by akva2 — APPROVED** [review]
Hit the green.

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins build this please

**Comment by bska** [comment]
PR is approved and green.  I'll merge into master.

**Pull request merged**
