### PR TITLE
Test case for actionx.

### PR DESCRIPTION
**Pull request by tskille**
Following keywords trigged by Action
  - UDQ, WELPI, WELOPEN, GCONINJE

Notice that this test case will be expanded to also include GLIFTOPT and ACTIONX.

### CODE REVIEW

**Comment by joakim-hove** [comment]
Can this be merged? And then possibly updated at a later stage?

**Comment by tskille** [comment]
Yes I think it can.

**Comment by alfbr** [comment]
> Can this be merged?

Yes, this case is not in testing anyway. Since it also touches include files, let's ensure Jenkins is happy first.

**Comment by alfbr** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
OK - I'll kick Jenkins again - and merge if green.

**Comment by joakim-hove** [comment]
jenkins build this please

**Pull request merged**
