### PR TITLE
Adapt DRSDTCON test to test for multiple regions

### PR DESCRIPTION
**Pull request by totto82**
Depends on https://github.com/OPM/opm-simulators/pull/5527

Note that this PR also adds output of mass injection rates to CO2STORE_GW

### CODE REVIEW

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
@totto82 , can you merge the reference PR to this PR?  https://github.com/OPM/opm-tests/pull/1211

**Comment by totto82** [comment]
>can you merge the reference PR to this PR? https://github.com/OPM/opm-tests/pull/1211

Dont we need to merge the changes to the simulator first?

**Comment by GitPaean** [comment]
> Dont we need to merge the changes to the simulator first?

#1211 provides the update of the reference for this PR.  They need to go in together.  That is my view.

**Comment by GitPaean** [comment]
> Dont we need to merge the changes to the simulator first?

Now I see your point. That is also one way.   But these two PRs need to be merged anyway.

**Comment by totto82** [comment]
I cherry-picked the reference update to make it possible to test together.

**Pull request merged**
