### PR TITLE
[WIP] Well modelling test cases

### PR DESCRIPTION
**Pull request by rnyb**
Includes multiple DATA files for different types of well completions

### CODE REVIEW

**Comment by alfbr** [comment]
This is highly appreciated! Will take a thorough look over the week-end :-)

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
This is really good! Thanks a lot for this contribution. I don't think Flow currently supports AICDs, but having these simulation models will absolutely make it easier to develop that feature.

**Comment by alfbr** [comment]
This looks great! Only two nit-picks and this goes in. Please include license and copyright headers also on include files. Unless there is reason to change convention, please also follow the naming scheme for the .DATA files as outlined in the model2 cases. For instance, rename 1_MODEL3.DATA to 1_BASE_MODEL3.DATA, 2_MODEL3.DATA to 2_MSW_MODEL3.DATA, etc.

**Comment by bska** [comment]
I like the updates&mdash;thanks a lot.  I think these should go in now, but I'll defer the final merge decision to @alfbr.

I have just one remark, mostly for the other OPM developers.  If we at any point wish to convert some of these models into regression tests for the simulator then we'll probably have to disable the `TCPU` summary vector.

**Comment by bska** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
I can be wrong, it looks like not finished yet.  For the example with aquifer, I did not find the definition of aquifer.

**Comment by rnyb** [comment]
The numerical aquifer keywords (AQUNUM and AQUCON) are included in the newly added data file 4_NUMAQ_MODEL3.DATA

**Comment by GitPaean** [comment]
> The numerical aquifer keywords (AQUNUM and AQUCON) are included in the newly added data file 4_NUMAQ_MODEL3.DATA

Yes. AQUNUM is not supported yet.  I did not check it in the deck. Sorry for the noise.

**Comment by alfbr** [comment]
Perfect, merging!

**Pull request merged**
