### PR TITLE
adding more features to 2D_FETKOVICHAQUIFER.DATA

### PR DESCRIPTION
**Pull request by GitPaean**
to incorporate the recent development in Fetkovich aquifer modeling . 

The results are not verified with commercial simulator for this specific case, while the development is verified with other models.

### CODE REVIEW

**Comment by GitPaean** [comment]
jenkins build this update_data please

**Comment by GitPaean** [comment]
I am a little confused about how to update_data when creating PR in opm-tests. @akva2 , any hints?

Thanks.

**Comment by akva2** [comment]
never encountered this situation before, so it's not really handled. you have to merge this, then use some other PR to update data.

**Comment by GitPaean** [comment]
> never encountered this situation before, so it's not really handled. you have to merge this, then use some other PR to update data.

Okay. Then the master branch will be broken for a bit. 

People are welcome to comment about this PR. 

I will do it when few people are around.

**Comment by GitPaean** [comment]
@alfbr please comment whether changing the DATA set here is a welcomed change. The motivation is to put the development in the simulator under protection from unintentional damage.

**Comment by GitPaean** [comment]
by all means, I believe this PR enhances the features of testing. Unless someone really objects about the change, I intend to merge it by tomorrow morning and update the reference results.

**Comment by GitPaean** [comment]
It is also possible is this PR makes us not be able to visit the link https://github.com/OPM/opm-tests/pulls . I am not totally sure about it.

**Comment by GitPaean** [comment]
Merging this PR when few people are around, because the master will be broken for a little bit.

**Pull request merged**
