### PR TITLE
Create POLYMER-03-POLYMER.inc

### PR DESCRIPTION
**Pull request by OPMUSER**
Add missing include file.

### CODE REVIEW

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
Thanks for the update. but with the INCLUDE file provided here, we still can not run the case by default because the keyword parsing. 

Should we address it before merging the PR, David? @OPMUSER 

It is basically related to the `OPTIONS` keyword. 

```
Error: Unsupported keywords or keyword items:

  OPTIONS: keyword not supported
  In file: POLYMER-03.DATA, line 65

  OPTIONS: keyword not supported
  In file: POLYMER-03.DATA, line 1125

Error: Unrecoverable errors while loading input: Problem with keyword 
```

**Comment by OPMUSER** [comment]
Done.

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
thanks for the PR. I am getting it in now.

**Pull request merged**
