### PR TITLE
MULT Tests

### PR DESCRIPTION
**Pull request by OPMUSER**
New set of MULT test cases and documentation. See EIPC OPM Flow MULT Runs Rev-2.pdf file for documtation.

### CODE REVIEW

**Comment by blattms** [comment]
I am wondering whether we really want binary files in a repository. How much space does the zipping save.

**Comment by OPMUSER** [comment]
It is not so much the saving of space, but making the directory more organized. So that the cases that have been run with various version are easily identified.

**Comment by bska** [comment]
I like this version a lot and I think it should be merged into master.

**Comment by alfbr** [comment]
Excellent, I agree. In it goes :-)

**Pull request merged**
