### PR TITLE
Test case with MINPV and without PINCH

### PR DESCRIPTION
**Pull request by tskille**
This model is testing MINPV without PINCH keyword. Grid dimension is 1x1x10, one well is completed in cell 1,1,1 and cell 1,1,2 has become inactive from porevolume below threshold volume set with MINPV. 

Notice that this case is currently not supported correctly by OPM flow. Hence development is needed before this test can be put on regression testing.  However, this test case should be valuable for the developer fixing this issue.

### CODE REVIEW

**Comment by OPMUSER** [comment]
@tskille I have a PR that has been outstanding for some time that refactored the PINCH tests, and documented the results using Markdown (https://github.com/OPM/opm-tests/pull/878) - would be nice to get this in.

Concerning this PR: 

- I would consider renaming the case to PINCH10_NOPINCH.DATA, for better clarity.
- @bska prefers not to have RSM files in regression tests, although like most engineers, I think the RSM output is useful. However, consider dropping this - your call.
- I ran a case with no MINPV and the summary variables (WBHP, WOPR, BPR) were almost identical, which not is ideal. Thus, consider changing the block property from pressure to PV, and include all ten layers, so instead of BPR, use this instead:

```
BRPV
 1 1 1 /
 1 1 2 /
 1 1 3 /
 1 1 4 /
 1 1 5 /
 1 1 6 /
 1 1 7 /
 1 1 8 /
 1 1 9 /
 1 1 10 /
/
```
That way it is clear that MINPV knocks out layer two.

Apart from the above, this looks good and should be merged.

**Comment by tskille** [comment]
I'm happy to remove output of RSM file. It was not intention to include this. The case has also been renamed as you are suggesting. 

However, I do not see the point in changing from BPR to BRPV. Notice that the problem with current version of Flow is that the simulator is using pinch (setting up a connection from layer 1 to layer 3, over the layer 2).  This is not correct behavior. When keyword PINCH is not used, this inactive cell (1,1,2) should act as a barrier for vertical flow. Block pressure for cells below this barrier are used to verify that there are no communication.  

When running this case with Eclipse, results are as shown below. The main characteristics for this (very basic) test case is that BPR:1,1,X for X in [3,..10] should not change over time. 


```
            TIME       BPR:1,1,1      BPR:1,1,10       BPR:1,1,2       BPR:1,1,4       BPR:1,1,5       BPR:1,1,6       BPR:1,1,7       BPR:1,1,8       BPR:1,1,9
        0.000000      266.904358      268.297577        0.000000      267.227417      267.478271      267.708099      267.912384      268.032623      268.108826
        0.100000      258.931274      268.297577        0.000000      267.227417      267.478271      267.708099      267.912384      268.032623      268.108826
        0.300000      242.954849      268.297577        0.000000      267.227417      267.478271      267.708099      267.912384      268.032623      268.108826
        0.600000      219.443893      268.297577        0.000000      267.227417      267.478271      267.708099      267.912384      268.032623      268.108826
        1.000000      188.593750      268.297577        0.000000      267.227417      267.478271      267.708099      267.912384      268.032623      268.108826
        2.000000      161.840942      268.297577        0.000000      267.227417      267.478271      267.708099      267.912384      268.032623      268.108826
        3.000000      151.228683      268.297577        0.000000      267.227417      267.478271      267.708099      267.912384      268.032623      268.108826
        4.000000      138.978394      268.297577        0.000000      267.227417      267.478271      267.708099      267.912384      268.032623      268.108826
        6.000000      114.892052      268.297577        0.000000      267.227417      267.478271      267.708099      267.912384      268.032623      268.108826
        8.000000      102.783958      268.297577        0.000000      267.227417      267.478271      267.708099      267.912384      268.032623      268.108826
       10.000000       96.590675      268.297577        0.000000      267.227417      267.478271      267.708099      267.912384      268.032623      268.108826
```

**Comment by OPMUSER** [comment]
> However, I do not see the point in changing from BPR to BRPV.
> 
> When running this case with Eclipse, results are as shown below. The main characteristics for this (very basic) test case is that BPR:1,1,X for X in [3,..10] should not change over time.
> 

My bad, I didn't check against E100 - you are correct with the block pressures.. Please merge when ready.

**Comment by tskille** [comment]
This PR has been open for some time. The bug fix from @blattms has been verified and I would like to put this case under regression testing. 

@OPMUSER has reviewed this and my understanding is that this is ready to be merged. If changes are required please let my know. what is needed before this can go in.

**Comment by bska** [comment]
> If changes are required please let my know

I think this is perfectly good as is and I'll merge into master.

**Pull request merged**
