### PR TITLE
update reference data for spe9 spe3 multpvv_model2 spe1 spe5 spe9group fetkovich_2d base_model2 spe12p editnnc_model2 ctaquifer_2d_oilwater spe1nowells polymer2d multflt_model2 faults_model_1 base_model_1 wecon_wtest polymer_injectivity multiply_tranxyz_model2 spe1_metric_vfp1 msw_2d_h spe1_foam hysteresis_model2 udq spe12 msw_3d_hfa multregt_model2 polymer_oilwater msw_model_1 swatinit_model2 nnc endscale_model2 multxyz_model2 spe1oilgas spe1thermal

### PR DESCRIPTION
**Pull request by jenkins4opm**
Reason: https://github.com/OPM/opm-simulators/pull/1955

libecl         = 4d92ac7982be3a7c5fbca1bcad694f020fd872af
opm-common     = b55e0731823f76d4e74beabdb61de229583c1c9a
opm-grid       = fdf4c702ff99539a52609f9a49631b72b39a07ab
opm-material   = a663bb45324df35734e3b6c79998e4e3fdea7a0b
ewoms          = a42a16fe2c5120e7e4a966ca538d32ec78f37c55
opm-simulators = 80859fd5379fde70d7e3ef1973b90450c5da41cf

### CODE REVIEW

**Comment by alfbr** [comment]
How about this one, should it be merged?

**Comment by GitPaean** [comment]
It needs to be merged when OPM/opm-simulators#1955 gets merged.

**Comment by alfbr** [comment]
Are you sure? A newer reference solution has already been merged. I would assume that you need to update again.

**Comment by GitPaean** [comment]
> I would assume that you need to update again.

You are absolutely correct. It is on the way.

**Pull request merged**
