### PR TITLE
OPERATE Keyword Tests

### PR DESCRIPTION
**Pull request by OPMUSER**
A series of tests to test the OPERATE keyword, currently only for the EDIT section.
The tests are designed around a "base case" and are generated in such a manner that the results should be identical, or very similar, to the "base case".

The tests confirm user feedback that the DEPTH, TRANX/Y/Z options are not working.

### CODE REVIEW

**Comment by alfbr** [comment]
jenkins build this please

**Comment by alfbr** [comment]
Thanks for the contributions! The changes looks good to me, and extends the coverage of the tests. Running checks just in case some of these are already in testing.Please let me know if you do not see this pull request as ready for merging.

**Comment by OPMUSER** [comment]
@alfbr Yes this can be merged. I have raised an issue https://github.com/OPM/opm-common/issues/2994 for the DEPTH, TRANX/Y/Z options not working.

**Comment by alfbr** [comment]
Thanks, in it goes.

**Pull request merged**
