### PR TITLE
Model2 prediction

### PR DESCRIPTION
**Pull request by tskille**
Adding prediction test cases for model2, based on model 9_EDITNNC_MODEL2.DATA. 

These cases are using the same include files for well completions and msw definitions as existing test cases 0A1-0A4, STW and MSW. 

Data decks for cases 0A1 to  0A4 is modified, but this is only cosmetic. WELSPECS keyword is moved from include file to the main deck file.

### CODE REVIEW

**Comment by bska** [comment]
jenkins build this please

**Comment by tskille** [comment]
@bska, I have now modified the PR. I have not removed the changes to model2/include/summary.inc. This is used by a number of models already being under regression testing.

**Comment by bska** [comment]
> I have now removed the changes to the include file **model2/include/summary.inc**.

To be honest, I think you can keep those changes in place if you want to.  It "just" means we'll have to update the reference solutions to account for the new vectors.  I also have a tiny PR in the pipeline that will be a very suitable candidate for updating those reference solutions.

If you'd rather merge this update in the current state&mdash;without the additional summary vectors&mdash;then I'll be happy to do so too.

**Comment by alfbr** [comment]
Fantastic to see these test cases ready for continuous integration testing! Please also include license and copyright headers for include files prod4_compl.inc and prod4_msw_def.inc. That is all from me, it is all yours @bska

**Comment by tskille** [comment]
> include license and copyright headers for include files prod4_compl.inc and prod4_msw_def.inc. 
Done, I missed i few there

@bska, I have already remove the additional summary vectors. These are cases that we are working on supporting now. I will update with a few extra vectors when these models are ready for regression testing.

**Comment by bska** [comment]
> @bska, I have already remove the additional summary vectors. These are cases that we are working on supporting now.

Very good.  I'll rerun the build check just to confirm.

> I will update with a few extra vectors when these models are ready for regression testing.

:+1:

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
Build check is green.  I'll merge into master.  Thanks a lot for the updates.

**Pull request merged**
