### PR TITLE
Test datasets for vertical scaling of relative permeabilities: KRW,KRWR &c

### PR DESCRIPTION
**Pull request by bska**
This is a rebased and slightly reworked version of PR #367.

---

### Commit message included from original PR ###

These test datasets contain tests of combinations of:
* SCALECRS = YES / NO
* KRW
* KRWR
* Other vertical scaling

NOTE: ENDSCALE keyword also needs to be used in the RUNSPEC section

---

Supersedes and closes #367.

### CODE REVIEW

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
I have verified that the [regression failures](https://ci.opm-project.org/job/opm-tests-PR-builder/134/#showFailuresLink) caused by this PR are all of the same form; new block-related saturation and relative permeability summary vectors added in [`model2/include/summary.inc`](https://github.com/OPM/opm-tests/pull/723/files#diff-b30b132e2364d4e3b9f23282ef828b2a04adc73652f3b1c32febc9e8cf6c452d).  It is therefore safe to update the reference solutions for these changes.

I will try to run `update_data` from here in the hope that our earlier fix to `update_reference_data.sh` (OPM/opm-simulators#3799) is sufficient to also restore that ability.

**Comment by bska** [comment]
jenkins build this update_data please

**Comment by akva2** [comment]
error: Terminal is dumb, but EDITOR unset
Please supply the message using either -m or -F option.

Something messes up this part. Need to look closer (not now).

**Comment by bska** [comment]
> Something messes up [commit message generation]. Need to look closer (not now).

Sure thing.  Please let me know if there's anything I can do to assist you.

**Comment by alfbr** [comment]
The data sets look good from my end. Merge at your convenience.

**Comment by bska** [comment]
> The data sets look good from my end. Merge at your convenience.

Thanks.  I will merge this once we've worked out what's preventing us from updating the reference solutions.  This PR adds a few more summary vectors to an include file that's used by multiple existing integration tests and we need to update those reference solutions first.  @akva2 [said](https://github.com/OPM/opm-tests/pull/723#issuecomment-1028184572) he'd look into that issue, but I don't know if he's had the time to do this yet.

**Comment by alfbr** [comment]
> Thanks. I will merge this once we've worked out what's preventing us from updating the reference solutions. This PR adds a few more summary vectors to an include file that's used by multiple existing integration tests and we need to update those reference solutions first. @akva2 [said](https://github.com/OPM/opm-tests/pull/723#issuecomment-1028184572) he'd look into that issue, but I don't know if he's had the time to do this yet.

Ah, I was not aware that was still pending. Sure, just merge when it is resolved.

**Comment by alfbr** [comment]
Just noticed that the header description is identical for all cases, while the file name gives a hint at the difference. Great if you can add one more sentence to describe each in the header.

**Comment by bska** [comment]
> Just noticed that the header description is identical for all cases, while the file name gives a hint at the difference.

Good catch.  I've pushed an update to address this shortcoming.

**Comment by alfbr** [comment]
Thanks for the quick fix! No more comments from me, so merge whenever jenkins is happy.

**Comment by bska** [comment]
> merge whenever jenkins is happy.

I will merge this no later than tonight CET.  If we can't solve the Jenkins issue I'll use the older, dirtier approach that breaks the build for a while.

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
The updated reference solutions have been installed on the CI system.  I'm merging this now to bring the CI system back to a consistent state.

**Pull request merged**
