### PR TITLE
added: add well curves for parallel simulation

### PR DESCRIPTION
**Pull request by akva2**

### CODE REVIEW

**Comment by akva2** [comment]
this should be uncontroversial, proved working and is testing related so kinda my turf. shameless self-merge.

**Comment by blattms** [comment]
Cool, thanks.

**Comment by blattms** [comment]
But the parallel is not run by default, right? Hence this will only help if the previously merged PR did request a parallel run (and the wells were checked). Otherwise the bug might have sneaked in earlier.

**Comment by akva2** [comment]
yes for the PR builder you will have to run both. It's mainly for the post builder where both are always run.

**Pull request merged**
