### PR TITLE
Add case for flow_onephase_energy

### PR DESCRIPTION
**Pull request by goncalvesmachadoc**

### CODE REVIEW

**Comment by bska** [comment]
Thanks!  I think this looks good.  There is a license and a copyright, so I think we should merge this.  Any objections, @alfbr?

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
@alfbr : Any reservation towards merging this?

**Comment by alfbr** [comment]
No objections, sorry for not answering immediately.

**Pull request merged**
