### PR TITLE
2phase case for salt precip. and water evaporation

### PR DESCRIPTION
**Pull request by goncalvesmachadoc**

### CODE REVIEW

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
Hi @goncalvesmachadoc,

Is this PR ready for review/merging now or is there more work expected here?

**Comment by goncalvesmachadoc** [comment]
> Is this PR ready for review/merging now or is there more work expected here?

It's ready for review/merging. :)

**Review by bska — COMMENTED** [review]
> > Is this PR ready for review/merging now or is there more work expected here?
> 
> It's ready for review/merging. :)

Understood.  Thanks a lot for the test case.  I'll merge this into master.

**Pull request merged**
