### PR TITLE
Combined PRs 293 and 295

### PR DESCRIPTION
**Pull request by atgeirr**
Manually created since Jenkins cannot simultaneously use and update opm-tests PRs.

### CODE REVIEW

**Comment by atgeirr** [comment]
jenkins build this please

**Comment by alfbr** [comment]
Are there still issues we need to resolve?

**Comment by bska** [comment]
> Are there still issues we need to resolve?

I don't think there are any issues remaining from the implementation side.  There appears to be some conflicts in a couple of `.UNSMRY` files in this PR which may need manual intervention.

@akva2 : Any suggestions on the appropriate course of action for resolving this, #293, and #295, in addition to the OPM-Simulator PRs OPM/opm-simulators#2552 and OPM/opm-simulators#2553?

**Comment by akva2** [comment]
if things are dependent, they need to go into the same PR's. there is no way around it, we can only build with one PR per repo.

**Comment by alfbr** [comment]
This got too complicated. I suggest we take one PR at the time, and start with https://github.com/OPM/opm-simulators/pull/2553

**Comment by bska** [comment]
> if things are dependent, they need to go into the same PR's.

Okay, I don't think that's actually feasible here.  Instead I think we'll have to do a staggered sequence of commits.  I'd suggest the following sequence:

1. Close this and #295 and merge #293 as is.  This will possibly introduce a temporary test failures.

2. Update reference data from OPM/opm-simulators#2553 and commit the results along with the opm-simulators PR.

3. Then decide whether we still want/need OPM/opm-simulators#2552 and, if so, launch another data update from that PR and commit the result.

**Comment by alfbr** [comment]
Agreed. Closing this one now. Having https://github.com/OPM/opm-simulators/pull/2552 here was an error that probably stemmed from me mixing up PRs in opm-tests. That one will need some more iterations before it is ready for merge.

**Pull request closed without merging**
