### PR TITLE
Removed message limits, reduced run-time

### PR DESCRIPTION
**Pull request by alfbr**
Message limit is set at way below defaults, so terminal output stops before simulation finishes with single day time steps. Moreover, the simulation time is shortened as there seems to be no additional benefit prolonging it.

### CODE REVIEW

**Comment by alfbr** [comment]
jenkins build this update_data please

**Comment by bska** [comment]
> update_data

Sadly, you can't use that request from opm-tests itself.

**Comment by alfbr** [comment]
Thanks for the reminder!

**Comment by alfbr** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
I am merging this PR now the master branch will be broken a little while for this test.

**Comment by akva2** [comment]
intentionally breaking master is *never* ok. you should have manually merged the two PR's into one, tested, then merged.

**Comment by GitPaean** [comment]
> you should have manually merged the two PR's into one

Sure. I should have done that.  Sorry for not doing that.

**Pull request merged**
