### PR TITLE
Update Results for 2D Cases.

### PR DESCRIPTION
**Pull request by OPMUSER**
Update for 2D horizontal well results that were not available previously.

Ready for review.

### CODE REVIEW

**Comment by bska** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
Looks good to me now and I'll merge into master.

**Comment by GitPaean** [comment]
Hei, the resulting plots show some significant difference between our simulator and the commercial simulator.  My question is what is the purpose for the resulting plots?  Thanks. 

I did not follow this development before.

**Comment by OPMUSER** [comment]
@GitPaean The idea is to document the agreement or differences between the commercial simulator and OPM Flow, so we know where we may have an issue. For example, MSW-2D-HZ-01, where E100 STOPS with errors, whereas OPM Flow runs. Which would imply that we are not checking the well configurations to a sufficient detail. This is an issue as the results will be unreliable.

Hopefully, the above helps.

**Comment by tskille** [comment]
@OPMUSER, which version of Eclipse have you used to generate the Eclipse results shown on the results plotting ? or have you made changes to the input deck in order to complete the Eclipse simulations ?

**Comment by tskille** [comment]
> No changes to decks.

I have tested with 2021.4 and I'm getting errors. What have you done in order to continue the simulation beyond 14-DEC-2019 ?

**Comment by OPMUSER** [comment]
What cases are we talking about?

**Comment by tskille** [comment]
https://github.com/OPM/opm-tests/blob/master/msw/plots/ECL/MSW-2D-HZ-Field_Production_Comparison_Plot.png

**Comment by OPMUSER** [comment]
Sorry for the late reply. The reason for the discrepancy, after 2020, is that the decks are different. The following is commented in E100, but active in OPM Flow:
```
--
--       WELL SEGMENT SPECIFICATION DATA
--
-- WELL  NODAL       LEN     WELL    DEPH    PRESS   FLOW
-- NAME  DEPTH       TUBING  VOLM    OPTN    CALC    MODEL
WELSEGS
'PROD01' 2512.5      2512.5  1.0e-5  'ABS'   'H--'   'HO'  /
--
--       SEG   SEG   BRAN    SEG     TUBING  NODAL   TUBE   TUBE     XSEC  VOL
--       ISTR  IEND  NO      NO      LENGTH  DEPTH   ID     ROUGH    AREA  SEG
          2     2    1       1       2537.5  2537.5  0.3    0.00010           /
          3     3    1       2       2562.5  2562.5  0.2    0.00010           /
          4     4    2       2       2737.5  2537.5  0.2    0.00010           /
/
--
--       MULTISEGMENT WELL COMPLETION SEGMENT SPECIFICATION DATA
--
-- WELL
-- NAME
COMPSEGS
'PROD01' /
--
--      --LOCATION--  BRAN  TUBING  NODAL   DIR  LOC    MID    COMP    ISEG
--       II  JJ  K1   NO    LENGTH  DEPTH   PEN  I,J,K  PERFS  LENGTH  NO.
         20   1   1   1     2512.5  2525.0                                     /
         20   1   2   1     2525.0  2550.0                                     /
         20   1   3   1     2550.0  2575.0                                     /
         19   1   2   2     2637.5  2837.5                                     /
/
```

The reason is that on an old version of E100 that I had access to at the time, E100 stops with error messages:
```
@--WARNING  AT TIME     2960.0   DAYS    (14-DEC-2019):
 @           SEGMENT   5 IN WELL PROD01   HAS A DEPTH CHANGE OF              
 @           -2537.5  METRES  WHEREAS ITS LENGTH IS ONLY -2737.5  METRES .   
 @           THIS IS NOT PHYSICAL.                                           

 @--  ERROR  AT TIME     2960.0   DAYS    (14-DEC-2019):
 @           SEGMENT   5 IN WELL PROD01   HAS A LENGTH <OR= 0.0              

 @--  ERROR  AT TIME     2960.0   DAYS    (14-DEC-2019):
 @           SEGMENT   6 IN WELL PROD01   HAS A LENGTH <OR= 0.0              

 @--  ERROR  AT TIME     2960.0   DAYS    (14-DEC-2019):
 @           CONNECTIVITY ERROR IN WELSEGS  DATA FOR WELL PROD01  .          
 @              2 SEGMENTS ARE ISOLATED, INCLUDING SEGMENT    6     

```
So I commented the offending section out, for the final run on 2021.4.

**Pull request merged**
