### PR TITLE
adding ALL to the SUMMARY section for MICP.DATA

### PR DESCRIPTION
**Pull request by GitPaean**
There is no (almost) SUMMARY output for its current form.

### CODE REVIEW

**Comment by GitPaean** [comment]
Let us see if we can generate reference this way. Will get that PR here if successful.

**Comment by GitPaean** [comment]
jenkins build this update_reference please

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
Without summary output, the regression test does not check the well related summary and it is a little inconvenient to evaluate the regression failures.

**Review by bska — APPROVED** [review]
Looks good and I'll merge into master.

**Pull request merged**
