### PR TITLE
adding WELSPECS to RPTSCHED in SPE9_CP_GROUP.DATA

### PR DESCRIPTION
**Pull request by GitPaean**
to activate the output of the group report.

### CODE REVIEW

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
@joakim-hove , please refer to the test failure as follows, 

https://ci.opm-project.org/job/opm-tests-PR-builder/42/testReport/junit/(root)/mpi/compareECLFiles_flow_SPE9_CP_GROUP/

It is probably the same failure that was referred in https://github.com/OPM/opm-common/pull/1773 . 

But to me, the failure might be related to how you compile it and I saw different symptom on my machine (got stuck).

**Comment by GitPaean** [comment]
Or it is also possible a different bug.

**Comment by joakim-hove** [comment]
jenkins build this opm-common=1781 please

**Comment by joakim-hove** [comment]
I realize this was mainly created to illustrate a bug; but I suggest we merge it along with https://github.com/OPM/opm-common/pull/1781?

**Comment by GitPaean** [comment]
> I realize this was mainly created to illustrate a bug; but I suggest we merge it along with OPM/opm-common#1781?

It is good to merge it, then the new development will be tested and protected.

**Comment by joakim-hove** [comment]
jenkins build this opm-common=1781 please

**Pull request merged**
