### PR TITLE
WCONPROD Results Update

### PR DESCRIPTION
**Pull request by OPMUSER**
Update WCONPROD results using markdown. Only one test works.

Re-saved DATA files via Kate to get Linux EOF (hopefully).

### CODE REVIEW

**Comment by alfbr** [comment]
Is this ready for review?

**Comment by OPMUSER** [comment]
I just refreshed the runs based on Friday's master and updated the documentation. The results are the same as before. So yes this is ready for review.

**Comment by bska** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
Thanks.  I'll merge into master.

**Pull request merged**
