### PR TITLE
test WELTARG and WEFAC

### PR DESCRIPTION
**Pull request by totto82**
I suggest the following changes to cover WEFAC and WELTARG

### CODE REVIEW

**Comment by totto82** [comment]
Note this will need OPM/opm-simulators#2235 and OPM/opm-common#1351 to fly

**Comment by akva2** [comment]
this will not affect any tests - there are no tests using SPE9_CP.DATA, only SPE9_CP_SHORT and SPE9_CP_GROUP

**Comment by totto82** [comment]
Good point. I will add the same modifications to SPE9_CP_SHORT instead. Thanks for noticing!

**Comment by totto82** [comment]
I have made a new PR for SPE9_CP_SHORT

**Pull request closed without merging**
