### PR TITLE
Added small tests for PINCH functionality

### PR DESCRIPTION
**Pull request by blattms**
These simple tests are based on a vertical stack of 5 cells. There are tests with `PINCH GAP`, `PINCH NOGAP`, and without any `PINCH`. There are also reference solutions.

### CODE REVIEW

**Comment by alfbr** [comment]
This is really great, the MINPV+PINCH functionality is complicated. Good test coverage is paramount. Please remove the reference simulations from the pull request, opm-tests is only intended to contain reference solutions from Jenkins.

**Comment by blattms** [comment]
Done with cleanup.
Note that these tests are currently not used.

**Comment by alfbr** [comment]
> Done with cleanup.
Thank you!
> Note that these tests are currently not used.
No problem, I can add them later on.

Just one more comment, and this goes in. Please add a brief comment in each header to explain what is tested. The file names are not self-explanatory. (sorry for not noticing in my first comment)

**Comment by blattms** [comment]
Explaining comments added to all files.

**Comment by alfbr** [comment]
Perfect, thanks for being patient.

**Pull request merged**
