### PR TITLE
Adding more summary output to polymer cases

### PR DESCRIPTION
**Pull request by GitPaean**
WOPP, WIPP, WPI

mostly due to the fact that regression tests did not detect the mistake fixed by PR https://github.com/OPM/opm-simulators/pull/4655 .

### CODE REVIEW

**Comment by GitPaean** [comment]
@akva2  how to elegantly generate the reference output due to this PR?

**Comment by GitPaean** [comment]
I think I push more things than needed in this PR, will update it later after a meeting. 

But the question above is still valid.

**Comment by GitPaean** [comment]
The PR content is right now.

**Comment by akva2** [comment]
there is no elegant way. i have tried to add some functionality for this, but it doesn't currently work as it should. you have to  generate a update PR with this PR, then you have to merge this PR with the generated one by hand.

**Comment by GitPaean** [comment]
> there is no elegant way. i have tried to add some functionality for this, but it doesn't currently work as it should. you have to generate a update PR with this PR, then you have to merge this PR with the generated one by hand.

Sure. Thanks. I will do that.

**Comment by akva2** [comment]
jenkins build this update_data please

**Comment by akva2** [comment]
hrm. that did not work. let's abuse some other PR then.

**Comment by akva2** [comment]
now pull https://github.com/OPM/opm-tests/pull/967 into this branch.

**Comment by GitPaean** [comment]
There is some complication
```
kaib@kai-ws:~/OPM-master-test/opm/opm-tests$ git pull git@github.com:jenkins4opm/opm-tests.git update_opm-common_3525
From github.com:jenkins4opm/opm-tests
 * branch              update_opm-common_3525 -> FETCH_HEAD
error: The following untracked working tree files would be overwritten by merge:
	spe1_solvent/SPE1CASE2_SOLVENT_FOAM.DATA
Please move or remove them before you merge.
Aborting
```

**Comment by GitPaean** [comment]
Okay. I need to update the master branch.

**Comment by akva2** [comment]
rebase on master first.

**Comment by GitPaean** [comment]
jenkins build this please

**Pull request merged**
