### PR TITLE
commenting out COMPS NCOMPS CNAMES

### PR DESCRIPTION
**Pull request by GitPaean**
for testing how the compositional keywords are used in blackoil simulation

### CODE REVIEW

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
It looks like those keywords can be removed.  Will do the same with H2STORE_GASWAT.

**Comment by GitPaean** [comment]
@totto82 , do you know those keywords are used in the simulation, can they be removed?

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by totto82** [comment]
They are needed if DENAQA or VISCAQA are used to map the coefficients in these keywords to the right components. 

Since CO2STORE and H2STORE is a special case where compositional and blackoil are mixed maybe we need a check if(!co2store) output compositional stuff. Or even better would be to compute the needed output for CO2STORE to make it compatible with compositional type output. As a first attempt I would suggest a if(!co2store) type solution.

**Comment by GitPaean** [comment]
> They are needed if DENAQA or VISCAQA are used to map the coefficients in these keywords to the right components.
> 
> Since CO2STORE and H2STORE is a special case where compositional and blackoil are mixed maybe we need a check if(!co2store) output compositional stuff. Or even better would be to compute the needed output for CO2STORE to make it compatible with compositional type output. As a first attempt I would suggest a if(!co2store) type solution.

Thanks for the prompt response. I am not aware of the setup of keywords `DENAQA or VISCAQA `.   Let me assume both `co2store` and `h2store` are pure black oil implementation for now.  we might need to revisit these at a later stage when we get there.

**Pull request closed without merging**
