### PR TITLE
Disjoint LGR test added

### PR DESCRIPTION
**Pull request by aritorto**
Currently, we support CpGrid with disjoint LGRs. A test has been added.

### CODE REVIEW

**Comment by aritorto** [comment]
jenkins build this please

**Comment by bska** [comment]
> jenkins build this please

@aritorto : You **may** not be on the list of users who can trigger builds in this repository.  I'll run a build for you now, but @akva2  can check if you're on the right lists and add you if not.

**Comment by bska** [comment]
jenkins build this please

**Comment by akva2** [comment]
on the list now.

**Review by bska — APPROVED** [review]
Looks good to me and I'll merge into master.   Thanks a lot for the new test case, @aritorto!

**Pull request merged**
