### PR TITLE
added very simple adjoint test

### PR DESCRIPTION
**Pull request by hnil**
Start on making simple test cases to test adjoint code. This is at the moment only used for regression tests of cases checked using MRST.

### CODE REVIEW

**Comment by alfbr** [comment]
Thanks for the contribution, this is welcome! Please include copyright notice and license in file headers. It seems you have added all output files. Currently we try to only include files that are actually tested. If you remove the files, then please also remove them from the git history, since it will keep download times for the repository lean.

**Comment by andlaus** [comment]
> If you remove the files, then please also remove them from the git history, since it will keep download times for the repository lean.

I thought this was only the case for opm-data?

**Comment by alfbr** [comment]
@hnil please inform when you believe it is ready for merging.

**Comment by akva2** [comment]
Can one of the admins verify this patch?

**Comment by alfbr** [comment]
@hnil have you forgotten this one?

**Comment by alfbr** [comment]
@hnil please inform if you still want this test case in. Unless commented, this PR will be closed early next week.

**Comment by alfbr** [comment]
Closing as warned, please re-open if you still want to get it merged.

**Pull request closed without merging**
