### PR TITLE
Add data file for small foam test case.

### PR DESCRIPTION
**Pull request by atgeirr**
The test case is based on SPE1CASE2 and is completely artificial. No attempts have been made to make it realistic at this point.

### CODE REVIEW

**Comment by alfbr** [comment]
Consider including Sintef in the copyright header.

**Comment by alfbr** [comment]
There are no comments regarding the foam related keywords in the file. If you intend this to be a regression test, then please include some explanatory lines. Preferably a couple of lines in the header explaining what you test, and then a few lines for the keywords with a brief explanation. Otherwise this looks great, thanks for taking the time to create the data set!

**Comment by atgeirr** [comment]
Comments added and force-pushed.

**Comment by alfbr** [comment]
Excellent, in it goes!

**Pull request merged**
