### PR TITLE
Two extra test cases for gas export and fixed error in 9_2B

### PR DESCRIPTION
**Pull request by tskille**
Two extra test cases which is targeted to test item3 and 4 in GCONSALE. 
Fixed one mistake in in existing test case   

- 9_2B_DEPL_GCONPROD_2L_MSW.DATA  
- 9_2B_DEPL_GCONPROD_2L_STW.DATA

### CODE REVIEW

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
I'm preparing to merge OPM/opm-common#1749 which will also require updating the reference data. I'll merge this now, temporarily creating test failures, and then update everything as part of merging the other PR.

**Comment by alfbr** [comment]
> I'll merge this now, temporarily creating test failures

It should not, none of these cases are tested yet.

**Comment by bska** [comment]
>> I'll merge this now, temporarily creating test failures
> 
> It should not, none of these cases are tested yet.

Right, but this PR requests a couple of new summary vectors in an include file that is common to many other, existing regression cases.  That's what causing the test failures.

**Comment by alfbr** [comment]
Ah, I see, very impressed you picked up on that :-)

**Pull request merged**
