### PR TITLE
Create ACTIONW_WPIMULT.DATA

### PR DESCRIPTION
**Pull request by OPMUSER**
Simple ACTIONW test for testing ACTIONW implementation.

### CODE REVIEW

**Comment by OPMUSER** [comment]
Forgot to mention, that although this is okay to add to master, the case will not run as the keyword is not currently implemented.Implementation is ongoing.

**Comment by GitPaean** [comment]
Just for variants, maybe there can be some `WPIMUIT` keywords with non-defaulted connection and segment information?

**Comment by OPMUSER** [comment]
Some people are never happy :-)

Yes I have a plan for a few more tests based on the R full field model utilization, including nested ACTIONW blocks. I kept this first test very simple so @blattms can get test the basics first.

**Comment by alfbr** [comment]
> Forgot to mention, that although this is okay to add to master, the case will not run as the keyword is not currently implemented.Implementation is ongoing.

That is not needed for adding the data set to opm-tests. Review coming :-)

**Comment by alfbr** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
> Some people are never happy :-)

I am very happy, it was a suggestion to extend the tested scenarios.

**Comment by alfbr** [comment]
Data set looks good, nothing to add. Merging!

**Pull request merged**
