### PR TITLE
update reference data for multpvv_model2 fetkovich_2d base_model2 editnnc_model2 ctaquifer_2d_oilwater polymer2d multflt_model2 polymer_injectivity multiply_tranxyz_model2 spe1_metric_vfp1 msw_2d_h hysteresis_model2 msw_3d_hfa multregt_model2 polymer_oilwater swatinit_model2 nnc endscale_model2 multxyz_model2

### PR DESCRIPTION
**Pull request by jenkins4opm**
Reason: https://github.com/OPM/opm-common/pull/1255

opm-common     = 88c1b28e0416804996d883e8e2c953f0ea1e637a
opm-grid       = 3766d3c4145f2a06754f6d5aa3ac718580ff3639
opm-material   = 7a136e84f2d9297bb60a9526cbd64cf0b4b09663
opm-models     = b2019c96b2d71a272a312d5a3162f0f403fe542a
opm-simulators = 88c1b28e0416804996d883e8e2c953f0ea1e637a

### CODE REVIEW

**Comment by joakim-hove** [comment]
Would it be possible to hook up a binary to this PR machinery which could post a human readable summary back as a github comment?

**Comment by akva2** [comment]
absolutely, no problem hooking up such a thing. the thing needs to exist though.

**Comment by bska** [comment]
>> Would it be possible to hook up a binary to this PR machinery which could post a human readable summary back as a github comment?
>
> absolutely, no problem hooking up such a thing. the thing needs to exist though.

Do we need anything more than
```sh
for f in $(changed files); do
    echo "--> ${f}";
    diff -u <(convertECL "${ref}/${f}") <(convertECL "${new}/${f}")
done
```
:question: 

This obviously assumes Bash and `$(changed files)` may be a bit tricky to express correctly, but you get the idea.

**Comment by bska** [comment]
I'm merging this into master now to install the `ISEG[0]` fix in OPM/opm-common#1255.

**Pull request merged**
