### PR TITLE
Merge branch 'master' of github.com:jilocode/opm-tests into NOPINCH

### PR DESCRIPTION
**Pull request by jilocode**

### CODE REVIEW

**Comment by alfbr** [comment]
It seems this Pull request was unintended?

**Comment by bska** [comment]
Hi @jilocode,

Would you be able to "rebase" the work on top of the current master sources?  Doing so will fix the merge conflicts and, additionally, remove the merge commits.  That, in turn, will make the commit history easier to read in case we need to trace the origins of an issue at a later date.

Feel free to reach out to me if you'd like me to assist you in rebasing the commits.

**Comment by bska** [comment]
Hi @jilocode,

You did not respond to my [earlier query](https://github.com/OPM/opm-tests/pull/691#issuecomment-984710094).  Do you still want to merge this PR?  If so, please rebase the work on top of the current master branch.  If not, I think we should close the PR soon.

**Comment by bska** [comment]
> I think we should close the PR soon.

Closing this per agreement in private communication.

**Pull request closed without merging**
